[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "curl", "wget"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.release]
cmds = [
    ". /opt/venv/bin/activate && python manage.py migrate",
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application"
