# Generated by Django 4.1.8 on 2025-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userpreference_task_task_users_task_date_47911f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
